# Generated by Django 6.1 on 2026-08-14 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_personalvault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvault',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='vault_files/'),
        ),
        migrations.AlterField(
            model_name='personalvault',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserVaultProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vault_pin', models.CharField(default='1234', max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
