# Generated by Django 6.1 on 2026-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_personalvault_file_alter_personalvault_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaultprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uservaultprofile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uservaultprofile',
            name='vault_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
